language: node_js
node_js:
  - "0.10"
before_install: npm install -g istanbul codeclimate-test-reporter
services:
  - mongodb
deploy:
  provider: npm
  email: "hashan.punchihewa@gmail.com"
  api_key: "x28n90Y4CrvfNcgJhXmtBgTIEFJxHHuUTkyef0nKXxJPL+gcwDpxrnCB3vHWIjcrRYQvfAqXSJ4Kh/2zj/dlE74UdVoiEDYbtBbNw2qU/duRQRMnabLZK9UGhdBskyvk30bMMckJlUdzJGMTKJtDS3HVJFYU51k9gu/gvS7CDeE="
  on:
    tags: true
    all_branches: true