language: node_js
node_js:
- '0.10'
before_install: npm install -g istanbul codeclimate-test-reporter
services:
- mongodb
addons:
  code_climate:
    repo_token: 5b51beab79fe71502b55863bf33878bf5fd061908361050d2f10ff2554cac9f2
after_script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && cat coverage/lcov.info | codeclimate'
deploy:
  provider: npm
  email: hashan.punchihewa@gmail.com
  api_key:
    secure: Xtw/614l5c1sN4VOoNGAaOXlBONFxiYEER6+19ScQf2RORIsUWUCshWWqcbZlOpt/5jU6QOUiaQFpPMom+eSW0+0aup2YnMPNsBDzcFuOMuBZJB9A9CMwRkE0QXbpr6S6BNjhrRz7XTmFfIfb6bxdimxWLjbPOd7e0VSW6Bu4PQ=
  on:
    tags: true
    repo: TheMuses/achilles-mongodb
    all_branches: true
